<?php
// $Id$

/**
 * @file
 * Main module file for the quickmigrate aegir frontend.
 */

/**
 * Implementation of hook_perm():
 */
function quickmigrate_perm() {
  return array('administer quickmigrate');
}

/**
 * Implementation of hook_hosting_tasks().
 */
function quickmigrate_hosting_tasks() {
  $tasks = array();
  $tasks['site']['quickmigrate'] = array(
    'title' => t('Quick migrate'),
    'description' => t('Quick migrate the site.'),
    'access callback' => 'quickmigrate_task_access'
  );
  return $tasks;
}

function quickmigrate_task_access($node, $task) {
  return TRUE;
}
